### ISSUE TITLE
Can you provide an APK?

### ISSUE THREAD

**Issue by wong2** [jirawatee/FCM-Android#3]

**Comment by jirawatee** [comment]
If you want try it you just create an Android app in Firebase Console, download google-services.json then paste it in your app folder.

Finally if you want to send notifications via app you just replace YOUR_SERVER_KEY in MainActivity.java by SERVER_KEY from Firebase Console.

**Comment by wong2** [comment]
@jirawatee I'm a backend developer, it would be useful if I can download an APK and use it as a playground for test sending notification from server

**Comment by emailsubjekt** [comment]
Dude, you can't ask him for an APK, at least offer the man some money, he provided the code for free already. Don't be a douche.
