### ISSUE TITLE
Differing notification behaviour when app is in background

### ISSUE THREAD

**Issue by datag** [jirawatee/FCM-Android#5]
When receiving a push while in foreground, the intended behavior as such like showing the demo image works fine. But when in background, FCM handles the notification itself and just shows title/body without the image.

When the "notification" payload is set, FCM on the device handles the notification itself. When omitted (just "data"), the app itself is responsible for showing the notification and is able to show an image.

What about sending just "data" with properties "title", "body" and "picture". The field "priority" might be set to "high", as pure-data-pushes are priority "normal" by default.

In ```MyFirebaseMessagingService``` have code like:

```java
	private void sendNotification(RemoteMessage.Notification notification, Map<String, String> data) {
		// NOTE: use "notification" payload if set (fallback)
		String title = (notification == null) ? data.get("title") : notification.getTitle();
		String body = (notification == null) ? data.get("body") : notification.getBody();

		Bundle bundle = new Bundle();
		bundle.putString("title", title);
		bundle.putString("body", body);
		bundle.putString(FCM_PARAM, data.get(FCM_PARAM));
		// ...

		NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, getString(R.string.notification_channel_id))
				.setContentTitle(title)
				.setContentText(body)
				/* ... */
				;
```

What do you think?

**Comment by jirawatee** [comment]
Sending just "data payload" is also my technique when I want to see 100% of BigPicture in notification in Android.

However, now we have a way to display an image in notification both Android and iOS even your app is in the background by sending an image in the notification payload either Firebase Console or coding. https://firebase.google.com/docs/cloud-messaging/android/send-image
